version: '3.8'
services:

  database:
    container_name: drizzle-pgsql
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - 4321:5432
    volumes:
      - ./data:/var/lib/pgsql/data

  server:
    container_name: drizzle-server
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
