version: '3.8'
services:

  database:
    container_name: drizzle-pgsql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: pokemon_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 4321:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    container_name: drizzle-server
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
