version: '3.9'
services:

  database:
    container_name: drizzle-pgsql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: pokemon_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    container_name: drizzle-server
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_started
      database:
        condition: service_healthy

  migration:
    container_name: drizzle-migration
    build: .
    command: sh -c "npm run migrations:push"
    volumes:
      - .:/app
    links:
      - database
    networks:
      - postgres
    depends_on:
      database:
        condition: service_healthy

networks:
  postgres:
    driver: bridge
